# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-28 02:44
from __future__ import unicode_literals

import WebApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_color', django_enumfield.db.fields.EnumField(default='r', enum=WebApp.models.ColorStyle)),
                ('car_size', django_enumfield.db.fields.EnumField(default=1, enum=WebApp.models.SizeStyle)),
                ('car_time_created', models.DateTimeField(auto_now_add=True)),
                ('car_time_changed', models.DateTimeField(auto_now=True)),
                ('car_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
